# Start of script
# These are supported funding model platforms by GitHub. I am using 5 out of 8 of the following sites.
# Don't fall for scams. If someone is claiming to be me, but is not one of the following listed entries, they are scamming you! Do not fall for scams, and report it to me if you see suspicious/illegal activity.
# In use

github: seanpm2001 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]

# Not in use

# patreon: seanpm2001 # Creator page
# patreon: seanpm2001_software # Main page
# Replace with a single Patreon username
# open_collective: seanpm2001 # Creator page and main page
# ko_fi: seanpm2001 # Creator page and main page
# tidelift: error404 # I am not on TideLift, as it costs money. Anyone claiming to be me on here is not me. I cannot pay money for a service like this.
# community_bridge: error404 # I was unable to find the site, anyone claiming to be me on here is not me.
# liberapay: seanpm2001 # Creator page and main page
# issuehunt: seanpm2001 # Creator page and main page

# Never used

# otechie: error404 # I am not on Otechie, as it costs money. I tried to see if there was a free option, but even to have a domain here, it costs $49 a month. Anyone claiming to be me on here is not me. I cannot pay money for a service like this.
# Otechie is no longer supported by GitHub (circa sometime in 2024)
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

# File info

# File type: YAML source file (*.yaml *.yml)
# File purpose: Configuring funding settings for GitHub
# File version: 5 (2025, Monday, August 18th at 07:56 pm PST)
# Line count (including blank lines and compiler line): 34

# End of script
